-- CreateEnum
CREATE TYPE "AiPlatform" AS ENUM ('LIARA', 'OPENROUTER');

-- AlterTable
ALTER TABLE "ai_models" ADD COLUMN     "platform" "AiPlatform"[] DEFAULT ARRAY['LIARA']::"AiPlatform"[];


-- DataMigration: مدل‌هایی که همین الان هم روی کاتالوگ لیارا (models.seed.ts /
-- liara-models-import.xlsx) هستند و شناسه‌شان (name) دقیقاً همان چیزی است که روی کاتالوگ زنده‌ی
-- OpenRouter (بررسی‌شده در ۱۴۰۵-۰۶-۱۲ / 2026-09-02 از GET https://openrouter.ai/api/v1/models) هم
-- وجود دارد — یعنی امن است همین یک ردیف روی هر دو پلتفرم کار کند، بدون نیاز به ردیف دوم
-- (docs/PRD-openrouter-migration.md §۶.۳). ۱۳ مدل لیارا که این‌جا نیستند (عمدتاً embedding و
-- خانواده‌ی openai/gpt-image-1/1-mini/1.5/2 — که OpenRouter اصلاً به همین نام ندارد، طبق بررسی
-- STUDIO_IMAGE_GEN_MODEL در discovery-generation.service.ts) عمداً دست‌نخورده با پیش‌فرض
-- platform=['LIARA'] می‌مانند.
UPDATE "ai_models" SET "platform" = ARRAY['LIARA','OPENROUTER']::"AiPlatform"[]
WHERE "name" IN (
  'aion-labs/aion-2.0',
  'anthropic/claude-fable-5',
  'anthropic/claude-haiku-4.5',
  'anthropic/claude-opus-4',
  'anthropic/claude-opus-4.5',
  'anthropic/claude-opus-4.6',
  'anthropic/claude-opus-4.7',
  'anthropic/claude-opus-4.8',
  'anthropic/claude-opus-5',
  'anthropic/claude-sonnet-4',
  'anthropic/claude-sonnet-4.5',
  'anthropic/claude-sonnet-4.6',
  'anthropic/claude-sonnet-5',
  'deepseek/deepseek-chat-v3-0324',
  'deepseek/deepseek-chat-v3.1',
  'deepseek/deepseek-r1-distill-llama-70b',
  'deepseek/deepseek-v4-flash',
  'deepseek/deepseek-v4-pro',
  'google/gemini-2.5-flash',
  'google/gemini-2.5-flash-image',
  'google/gemini-2.5-flash-lite',
  'google/gemini-2.5-pro',
  'google/gemini-2.5-pro-preview',
  'google/gemini-3-flash-preview',
  'google/gemini-3-pro-image-preview',
  'google/gemini-3.1-flash-lite',
  'google/gemini-3.1-pro-preview',
  'google/gemini-3.1-pro-preview-customtools',
  'google/gemini-3.5-flash',
  'google/gemini-3.5-flash-lite',
  'google/gemini-3.6-flash',
  'google/gemini-3.7-flash',
  'google/gemma-3-27b-it',
  'meta-llama/llama-3.1-8b-instruct',
  'meta-llama/llama-3.3-70b-instruct',
  'meta-llama/llama-guard-4-12b',
  'minimax/minimax-m2.5',
  'minimax/minimax-m3',
  'mistralai/mistral-nemo',
  'moonshotai/kimi-k2-0905',
  'moonshotai/kimi-k2-thinking',
  'moonshotai/kimi-k2.5',
  'moonshotai/kimi-k2.6',
  'moonshotai/kimi-k2.7-code',
  'moonshotai/kimi-k3',
  'openai/gpt-4.1',
  'openai/gpt-4.1-mini',
  'openai/gpt-4o-mini',
  'openai/gpt-5',
  'openai/gpt-5-mini',
  'openai/gpt-5-nano',
  'openai/gpt-5.1',
  'openai/gpt-5.1-codex',
  'openai/gpt-5.1-codex-max',
  'openai/gpt-5.1-codex-mini',
  'openai/gpt-5.2',
  'openai/gpt-5.2-chat',
  'openai/gpt-5.2-codex',
  'openai/gpt-5.3-codex',
  'openai/gpt-5.4',
  'openai/gpt-5.4-mini',
  'openai/gpt-5.4-nano',
  'openai/gpt-5.4-pro',
  'openai/gpt-5.5',
  'openai/gpt-5.5-pro',
  'openai/gpt-5.6-luna',
  'openai/gpt-5.6-luna-pro',
  'openai/gpt-5.6-sol',
  'openai/gpt-5.6-sol-pro',
  'openai/gpt-5.6-terra',
  'openai/gpt-5.6-terra-pro',
  'openai/o1',
  'openai/o3',
  'openai/o3-mini',
  'openai/o3-pro',
  'openai/o4-mini',
  'openai/o4-mini-high',
  'perplexity/sonar',
  'perplexity/sonar-pro',
  'perplexity/sonar-reasoning-pro',
  'qwen/qwen-2.5-72b-instruct',
  'qwen/qwen-plus',
  'qwen/qwen3-235b-a22b-thinking-2507',
  'qwen/qwen3-32b',
  'qwen/qwen3-coder',
  'qwen/qwen3.5-flash-02-23',
  'qwen/qwen3.7-max',
  'tencent/hy3-preview',
  'x-ai/grok-4.20',
  'x-ai/grok-4.20-multi-agent',
  'x-ai/grok-4.3',
  'x-ai/grok-4.5',
  'x-ai/grok-4.6',
  'x-ai/grok-build-0.1',
  'xiaomi/mimo-v2.5',
  'xiaomi/mimo-v2.5-pro',
  'z-ai/glm-4.6',
  'z-ai/glm-5',
  'z-ai/glm-5.1',
  'z-ai/glm-5.2',
  'z-ai/glm-5.3'
);
